import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import CursorFollower from "./components/common/CursorFollower";
import Footer from "./components/Footer";
import GoUpBtn from "./components/common/GoUpBtn";
import Lenis from "./components/common/Lenis";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { ThemeProvider } from "./context/ThemeProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const powerGrotesk = localFont({
  src: "./fonts/PowerGrotesk-Regular.woff",
  variable: "--font-power-grotesk",
  weight: "100 200 300 400 500 600 700 800 900",
});

export const metadata: Metadata = {
  title: "Paweł Bilski",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${powerGrotesk.variable} flex flex-col`}
      >
        <Lenis>
          <CursorFollower />
          <ThemeProvider>
            <Header locale={locale} />
            <NextIntlClientProvider messages={messages}>
              {children}
            </NextIntlClientProvider>
            <GoUpBtn />
            <Footer />
          </ThemeProvider>
        </Lenis>
      </body>
    </html>
  );
}
